language: java
deploy:
  provider: releases
  api_key:
    secure: S2z4weKP0+/Ip/rvVzlPep3uEGA9cjzq82/OCUgNOWlkv3VrF6X2VAkZfz0TJGJCux+jokXalrItT1ePeWToGDwAf5g98R92QecvFdb6GwyFXIhFdoFCz9BgOD7FZqpFPQByBecBqTphQdKmraSlhCaRN3WwmSFtCt3xIPMNoYw=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-github-plugin
notifications:
  hipchat:
    rooms:
      secure: atecPf6BLb4OWHPXkEp1HfBpFFAT4oS+h0azZKsExAxdA8NNgI4q7+fYdtBhp4u3svnp3jea3YtuuIodiUHe9lTPTVx8mkEtT61B0HmhWJUQKaoMqQSJolV4ChY4dBe9PnPwntai3gJsoRhqWio6r2BHpOj+PhqJRSx0TbsvNFQ=
